{
    'name': 'Hospital Management',
    'version': '19.0.1.0.0',
    'category': 'Industries',
    'summary': 'Complete poa_hospital_managementital management: patients, doctors, appointments, nurses — all in Odoo',
    'author': 'Harsh Tankariya',
    'website': 'https://www.itsedgar.tech/',
    'support': 'info.edgarteam@gmail.com',
    'license': 'LGPL-3',
        'depends': ['mail'],
    'data': ['security/ir.model.access.csv',
        'views/menu.xml',
        'views/patient_view.xml',
        'views/female_patient_view.xml',
        'views/male_patient_view.xml',
        'views/doctor_view.xml',
        'views/appointment_view.xml',
        'views/nurses_view.xml'],
    'images': ['static/description/banner.png'],
    'installable': True,
    'application': True,
    'auto_install': False,
}
